### ISSUE TITLE
Non-unicode characters in pw.xml?

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#144]
When I was meddling with pw.xml for scraping Abbrv, I came across one entry where my windows CMD threw one error

```
UnicodeEncodeError: 'charmap' codec can't encode character u'\xa8' in position 1
5: character maps to <undefined>
```

When I enquired why this error came, it turned out to be the following entry in pw.xml
```
<H1><h><key1>akftaprayatna</key1><key2>akftaprayatna</key2></h><body><gram n="Adj">Adj.</gram> <i>der sich nicht angestrengt hat</i> <ls>MAHA7BH.Einl.17¨a.</ls> PW188</body><tail><L>188</L><pc>1003-1</pc></tail></H1>
```

Specifically `¨` is the culprit I guess.

Count with notepad++ said there are 170 such matches

**Comment by drdhaval2785** [comment]
Similar is the case with '›'. Is it needed actually ?

**Comment by drdhaval2785** [comment]
Same with 'ý'. 
Is it needed.
It is not being rendered properly.

Dictionary is 2 superscript.
![capture](https://cloud.githubusercontent.com/assets/5755132/11019628/dcf1bdf8-8626-11e5-84f5-340008970df6.png)

Digital dictionary is 
![capture](https://cloud.githubusercontent.com/assets/5755132/11019631/055a1844-8627-11e5-8c25-76acb39dde88.png)

**Comment by gasyoun** [comment]
ý -> 2 superscript = footnote.
› -> ,

![akftaprayatna](https://cloud.githubusercontent.com/assets/80761/11020132/a472d106-8626-11e5-96fa-5217f3a048b5.PNG)

**Comment by funderburkjim** [comment]
I confirm the character to be a hex 'a8'.  This character was in the original pw_orig.txt.  Since this original is in the cp1252 encoding, that explains why it shows as a diaresis [see](http://www.cp1252.com/).  

When pw_orig.txt was converted to unicode in utf-8 encoding (pw_orig_utf8.txt),  the coding of
this character was not changed.  In fact it has the same meaning in unicode ([reference](http://www.fileformat.info/info/unicode/char/a8/index.htm)).

An examination of another instance where this diaresis occurs is in akzigamya;  In both words,
the diaresis coded this way as a8 should be a comma.  

So, I suspect all of them should be changed to comma.

I'll generate a set of updates to do this change.

I am not sure why you got the error message
```
icodeEncodeError: 'charmap' codec can't encode character u'\xa8' in position 1
5: character maps to <undefined>
```

If this is from a Python program,  it might be due to the way you opened the file.
The correct way to open a utf-8 encoded file in Python 2.7 is to use the codecs module: 
```
import codecs
f = codecs.open(<filename>,"r","utf-8")   # open file for reading
f = codecs.open(<filename>,"w","utf-8") # open file for writing

```

Or, you might get this error if you generated output to stdout using the print statement.
To get around this issue for print statement where you are printing unicode data in utf-8 encoding,
here's one technique:
```
  out = [the unicode string you want to print, saved in the variable 'out'
  print out.encode('utf-8')
```

In a way, it's good that you didn't print the 'right' way, since by printing unicode the 'wrong' way,
you discovered this error in the digitization!

**Comment by drdhaval2785** [comment]
@funderburkjim 
Thanks for the python tip.
I am starting to learn it slowly.
So the abbreviation code was in my naive python coding.

**Comment by gasyoun** [comment]
Blue python of Jim and naive of Dhaval.
What a family. :warning:

**Comment by drdhaval2785** [comment]
`®` is also hex 'ae'.
The plant marker.

**Comment by funderburkjim** [comment]
Re `® is also hex 'ae'.`

I view this not as a bug, but as an intentional markup feature of pw.txt. It is so documented in pw-meta.txt.

We could enhance pw.xml by converting this to some more useful form , and correspondingly enhance disp.php  to take this into account.  But that is a separate issue.  If you feel it is important, we can address this separately, later.

**Comment by funderburkjim** [comment]
I've written a program to generate update records for the diaresis->comma change.  Since you're learning, I've added lots of comments.  The program and its two output files are [here](https://gist.github.com/funderburkjim/c4d6be42fa2c65c4a1eb).

The next comment describes how to do this update on your local copy of pw.

**Comment by funderburkjim** [comment]
1. make a subdirectory as follows pywork/correctionwork/correction-issue-144 
2. save the program and two output files here.  (You will only need pwupd.txt for the remaining steps).
3. in pywork, edit 'update.sh' and note the last step 
```
python updateByLine.py ../orig/pw2.txt manualByLine02.txt ../orig/pw.txt 
```
  edit the manualByLine02.txt file, and append pwupd.txt file to the end. Then save manualByLine02.txt.  Be sure your editor is using utf-8 encoding (it probably will be)
4. copy the python command above to clipboard, and paste it into a terminal (assume GitBash).
  Incidentally, the key-sequence 'shift-insert' is recognized as 'Paste' in both GitBash and cmd.exe.
  Then, (if the program hasn't run ), type 'return' in the terminal to get it to run. My terminal session now shows
```
$ python updateByLine.py ../orig/pw2.txt manualByLine02.txt ../orig/pw.txt
444 change records processed from manualByLine02.txt
281095 records read from ../orig/pw2.txt and written to ../orig/pw.txt
```
Note: You could run sh update.sh, but this would take a lot longer. That's the main reason I typically just run the last command of update.sh, as described.
5.  To finish the update process, first 
```
sh redo_hw.sh
```
 This regenerates pwhw2.txt from pw.txt
6. And, finally,
```
sh redo_xml.sh
```
This (a) makes pw.xml from pwhw2.txt and pw.txt,
(b) checks that pw.xml is valid xml relative to pw.dtd.  NOTE: Currently, this step doesn't work on the local version, since we don't have 'xmllint' on the local version.
(c) regenerates pw.sqlite, and copies it to web/sqlite folder.
   NOTE:  This requires sqlite3.exe on local version.  I described elsewhere how to get xampp's version of sqlite3.exe into the path.

**Comment by funderburkjim** [comment]
Regarding  'ý'.   This also is mentioned in the pw-meta.txt file.
And, as said there, appears to be a superscript 2, and occurs only in relation to the source 'VP'.

Certainly for display, it would be an enhancement to show this as superscript 2 (the unicode for this is \u00b2`).  The digitization DOES use superscript 2 character, but in another context, And since this is a different context, that may explain why a different symbol was used.

**Comment by gasyoun** [comment]
`How do you get a link to a PARTICULAR comment of an issue?` you click on the date of the post.  funderburkjim commented `6 hours ago` - if you click on the date the URL will change and that is the link you can share.

**Comment by drdhaval2785** [comment]
@funderburkjim 
My local pw.xml is now regenerated as documented by you in https://github.com/sanskrit-lexicon/CORRECTIONS/issues/144#issuecomment-154910475.

**Comment by drdhaval2785** [comment]
`›` is still pending.

3/4 handled. One pending to close the issue.

**Comment by funderburkjim** [comment]
@gasyoun - Thanks for the Github tip re clicking on date of comment :+1:

**Comment by funderburkjim** [comment]
Re 'ý -> 2 superscript = footnote.'     On my first reading, I missed the observation that that 2 superscript represents a footnote.   
How do you know this ?
Where is the footnote ? (it's not on the page(s) containing the 2 superscript).

**Comment by funderburkjim** [comment]
Re `›`

According to pw-meta.txt:
```
‹  (\u2039) 140933 := SINGLE LEFT-POINTING ANGLE QUOTATION MARK
                      ‹X› = non-italic text
›  (\u203a) 141104 := SINGLE RIGHT-POINTING ANGLE QUOTATION MARK

```

Based on the counts shown, there are 171 (= 141104 - 140933) more right-pointing angle quotation
marks in pw.txt than there are left-pointing angle quotation marks.   Assuming that these *should* occur in pairs to delimit non-italic text,  then there should be the same number of these two markup characters.   

The examination of the `<ls>` elements in pw.xml  which Dhaval is doing encountered some of these within the scope of the `<ls>` tag,   Based on the abbrvlist.txt file, there were 4 instances.
```
4 matches for "›" in buffer: abbrvlist.txt
  40912:HEMA7DRI.1,145.2.›@pratiyuvana@pratiyuvana@71374
  60775:17,87.›@visArin@visArin@105653
  61398:HEMA7DRI.2,a,101,5.›@vegaka@vegaka@106864
  75662:HEMA7DRI.1,18,20.19,8.›@sopaDa@sopaDa@129479
```
From an examination of each case in pw.txt  , my conclusion is that the right-pointing-angle-quotation character should simply be removed in these cases.

**Comment by funderburkjim** [comment]
Here are the change transactions for pw.txt for the removal of those four '›' characters.
To keep a local version in sync: 
1. copy and paste these records into the bottom of pw/pywork/manualByLine02.txt
2. install the changes using the steps 4-6 described in the [comment above](https://github.com/sanskrit-lexicon/CORRECTIONS/issues/144#issuecomment-155233261).
```
 ; 11/20/2015  remove selected '›' right-pointing-angle-quotation character in
; 4 records.
; Ref https://github.com/sanskrit-lexicon/CORRECTIONS/issues/144
147192 old <H1>100{pratiyuvana}1{pratiyuvana}¦ •n. {%wiederholtes Mischen%} ¯HEMA7DRI.1,145.2.› ƒPage4.144-2ƒ PW71376
147192 new <H1>100{pratiyuvana}1{pratiyuvana}¦ •n. {%wiederholtes Mischen%} ¯HEMA7DRI.1,145.2. ƒPage4.144-2ƒ PW71376
;
218697 old <H1>100{visArin}1{visArin}¦ ²1) •Adj. ³a) {%hervorkommend , hervorbrechend%} ¯C2IC2.1,25,14,71. #{guhA°} ‹so v.a.› {%aus der Höhle widerhallend.%} ³b) ‹* umhergehend.› ³c) {%sich verbreitend , umsichgreifend , sich ausbreitend%} ¯KA7D.3,15,¯C2IC2.1,2. •Nom.abstr. #{°ritA} •f. ¯17,87.› ²2) •*f. #{°riRI} {%®Glycine_debilis.%} PW105651
218697 new <H1>100{visArin}1{visArin}¦ ²1) •Adj. ³a) {%hervorkommend , hervorbrechend%} ¯C2IC2.1,25,14,71. #{guhA°} ‹so v.a.› {%aus der Höhle widerhallend.%} ³b) ‹* umhergehend.› ³c) {%sich verbreitend , umsichgreifend , sich ausbreitend%} ¯KA7D.3,15,¯C2IC2.1,2. •Nom.abstr. #{°ritA} •f. ¯17,87. ²2) •*f. #{°riRI} {%®Glycine_debilis.%} PW105651
;
221135 old <H1>100{vegaka}1{vegaka}¦ ‹am Ende eines› •adj. ‹Comp.› (•f. ‹vegikA)› ²1) {%Geschwindigkeit%} ¯HEMA7DRI.2,a,101,5.› ²2) {%Ausleerung.%} #{daSa°} {%zehn Ausleerungen bewirkend%} ¯BHA7PR.2,113. PW106862
221135 new <H1>100{vegaka}1{vegaka}¦ ‹am Ende eines› •adj. ‹Comp.› (•f. ‹vegikA)› ²1) {%Geschwindigkeit%} ¯HEMA7DRI.2,a,101,5. ²2) {%Ausleerung.%} #{daSa°} {%zehn Ausleerungen bewirkend%} ¯BHA7PR.2,113. PW106862
;
267535 old <H1>100{sopaDa}1{sopaDa}¦ •Adj. ²1) {%betrügerisch , unehrlich%} ‹(von Personen und Handlungen.› #{°m} •Adv. ¯HEMA7DRI.1,18,20.19,8.› ƒPage7.187-3ƒ ²2) {%nebst dem vorangehenden Laute.%} PW129477
267535 new <H1>100{sopaDa}1{sopaDa}¦ •Adj. ²1) {%betrügerisch , unehrlich%} ‹(von Personen und Handlungen.› #{°m} •Adv. ¯HEMA7DRI.1,18,20.19,8. ƒPage7.187-3ƒ ²2) {%nebst dem vorangehenden Laute.%} PW129477
```

**Comment by gasyoun** [comment]
Removed indeed.

**Comment by funderburkjim** [comment]
This is answer to question of 'where is the footnote', in the '2 superscript' issue.
The answer is that the list of works in PW(K)  has 2 Vishnupurana variants.

![image](https://cloud.githubusercontent.com/assets/6393033/11102100/8c46c6aa-8888-11e5-8855-82e11655328e.png)

Since the one with the superscript 2 is a version by Wilson, I propose to make one of the
the following changes in the digitization pw.txt
```
OLD
 ¯VP.ý1,153. 
NEW: option 1
 ¯VP.W.1,153.
NEW: option 2
¯VP.².1,153. 
```
and similarly for the others.  Thus, 'VP.W.' is the abbreviation for the Wilson variant, under option 1.  and 'VP.².'  is tthe abbreviation under option 2.

My preference is to use option 1, since there are several cases where two-word abbreviations occur  (X.Y.) , and thus 'VP.W.'  will be seen by programs as just another of these X.Y. forms.

Let me hear your comments as to which option to use.
When a consensus arises, I'll generate and install the changes.

**Comment by gasyoun** [comment]
Sure I would go for 2nd one, because I'm afraid if 1st one will be chosen, we will see `VP.W.` one day as a fully legal abbreviation and will wonder where did it came from, just like you wondered about the superscript. Not always there will be a program that will convert it to the needed item. I would use something more Unicode and universal. ASCII age is over, Jim.

**Comment by drdhaval2785** [comment]
I also endorse the second option.

**Comment by funderburkjim** [comment]
In working on the ý  change, three subcases are present:
*  ý followed by a digit is changed to ² followed by period followed by that digit
*  ý followed by a period is changed to ² followed by that period
*  ý followed by a space (4 cases) is changed to ² followed by that space.

These changes introduce a slight variance with the printed text, For instance, in the first case,
a more exact representation would be (see for instance headwords dakzaputra,SiMSapAyana): 
* ý followed by a digit is changed to ² followed by *space* followed by that digit

But introducing that space in pw.txt would cause further difficulties in interpreting the scope of the
'ls' element as coded in pw.txt, while using the 'period'' incurs no such difficulty.

**Comment by funderburkjim** [comment]
@drdhaval2785   The ý  now installed.

I think this issue can be now closed - will let you do the honors (in case there's something left to do that I've missed).

**Comment by gasyoun** [comment]
Small, but took so much effort. As usual, anyway.
