### ISSUE TITLE
Correction submission for pw.xml <ls> tags

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#146]
#143 is the parent for this.

As I would not venture to correct the pw.xml myself right now,
let me document the errors here for @funderburkjim to correct.

**Comment by drdhaval2785** [comment]
`<ls>A4C2V.GR2HJ.1,7,19.</ls>` -> `<ls>A7C2V.GR2HJ.1,7,19.</ls>`
![capture](https://cloud.githubusercontent.com/assets/5755132/11019330/14a19798-861b-11e5-851a-0b4194404df6.png)

All other refs have the second reading.

```
<H1><h><key1>zawpad</key1><key2>za/wpad</key2></h><body><noti>(stark</noti> <s>za/wpAd</s> <noti>)</noti> <divm type="e" n="1">1)</divm> <gram n="Adj">Adj.</gram> (<gram n="f">f.</gram> <s>za/wpadI</s> <divm type="n" n="a">a)</divm> <i>sechsfüssig.</i> <divm type="n" n="b">b)</divm> <i>sichs Schritte machend , ~ gemacht habend</i> <ls>TS.3,3,10,2.</ls><ls>A4C2V.GR2HJ.1,7,19.</ls> <divm type="n" n="c">c)</divm> <i>aus sechs Stollen bestehend.</i> <s>°pAt</s> <gram n="Nomin">Nomin.</gram> <gram n="f">f.</gram> <ls>Ind.St.17,179.</ls> <divm type="e" n="2">2)</divm> <gram n="f">f.</gram> <s>zawpadI</s> <noti>(vgl. auch u.</noti> <s>zawpada</s> <noti>)</noti> <divm type="n" n="a">a)</divm> <i>*Laus.</i> <divm type="n" n="b">b)</divm> <i>eine Art Composition</i> <ls>S.S.S.164.</ls> [Page6.288-3] PW116151</body><tail><L>116153</L><pc>6288-2</pc></tail></H1>
```

**Comment by drdhaval2785** [comment]
`A4RAJABH` -> `A4RAJABH`
Print Error

Present one
![capture](https://cloud.githubusercontent.com/assets/5755132/11019341/7e63ec8a-861b-11e5-8771-4001681d27b0.png)

Whereas all others have 
![capture](https://cloud.githubusercontent.com/assets/5755132/11019344/a2d7043a-861b-11e5-8c10-99b13e21381d.png)

and
![capture](https://cloud.githubusercontent.com/assets/5755132/11019348/ce336f10-861b-11e5-973d-6b8168b384a6.png)

etc.

**Comment by drdhaval2785** [comment]
`A72V.C2R` -> `A7C2V.C2R`

All others have C.
Because of wrong entry, the output is not displayed properly.
See
![capture](https://cloud.githubusercontent.com/assets/5755132/11019381/6d73b364-861c-11e5-8321-d1d6ac25d31f.png)

**Comment by drdhaval2785** [comment]
`A72V.Grhj` -> `A7C2V.Grhj`
Same as above
आश्वलायन

**Comment by drdhaval2785** [comment]
`A7APST.` -> `A7PST.`

Remove extra 'A'.

**Comment by drdhaval2785** [comment]
`A7APST.C2R` -> `A7PST.C2R`
Remove extra 'A'.

**Comment by drdhaval2785** [comment]
`A7BJABH` -> `A7RJABH`
Illegible scan

AryabhaTTIya.

![capture](https://cloud.githubusercontent.com/assets/5755132/11019391/5de7b106-861d-11e5-9a44-4f36ca552f7d.png)

**Comment by drdhaval2785** [comment]
`A7BJAV` -> `A7BJAV`
Not sure.

But it seems that 'Aby' is not proper for anything. 'Ary' is better.

**Comment by drdhaval2785** [comment]
A7BSH -> A7RSH
Print error.

All others are A7RSH. BR.

![capture](https://cloud.githubusercontent.com/assets/5755132/11019415/32f365e8-861e-11e5-8550-eee43eb27e1d.png)

**Comment by drdhaval2785** [comment]
`<ls>A7C2.</ls>` -> `<ls>kA7C2.</ls>`
Data Entry error

![capture](https://cloud.githubusercontent.com/assets/5755132/11019430/aba47aea-861e-11e5-811a-46010e332a22.png)

**Comment by drdhaval2785** [comment]
A7C2A.C2R -> A7C2VA.C2R

All others have second reading

**Comment by drdhaval2785** [comment]
`<ls>A7C2B,</ls> <ls>GR2HJ.3,6,7.</ls>` -> <ls>A7C2V.GR2HJ.3,6,7.</ls>
Tagging Error.
One entry split into two.

![capture](https://cloud.githubusercontent.com/assets/5755132/11019441/1faeb57c-861f-11e5-99f4-4eb76984d152.png)

**Comment by drdhaval2785** [comment]
A7C2BV.C2R -> A7C2V.C2R

All others have the second entry

**Comment by drdhaval2785** [comment]
`<ls>A7C2V.C2R.8,13,35.Man</ls> <noti>könnte aber auch</noti>` -> <ls>A7C2V.C2R.8,13,35.</ls> <noti>Man könnte aber auch</noti>
Tagging error.

Next 'Man' added in the ls tag.

**Comment by drdhaval2785** [comment]
`A7C2V.GR2HJ.AS` -> `A7C2V.GR2HJAS`
Wrong period.

Also note - Inconsistent Abbrv usage by the lexicographer.
Everywhere else he used A7C2V.GR2HJ. and here he uses A7C2V.GR2HJAS.

![capture](https://cloud.githubusercontent.com/assets/5755132/11019475/2d835e9a-8620-11e5-930f-9759c7ca867b.png)

**Comment by drdhaval2785** [comment]
`A7G4AN` -> `RA7G4AN`
OCR Error

![capture](https://cloud.githubusercontent.com/assets/5755132/11019492/a7749aca-8620-11e5-8825-c6e1047120d0.png)

**Comment by funderburkjim** [comment]
These corrections have been installed in PW.

The s3 backup of 'pw' environment (orig,pywork,web) has been regenerated.

The programs in sanskrit-lexicon/PWK/pw_ls  directory have been rerun.

Below is a description of a 'standard' form for submitting further literary source corrections.  There
is a variant of the 'generate.py' program which processes such a standard format.  This program is in directory pywork/correctionwork/issue-146/ (where pywork is as above).

Here is the change.txt file used for the corrections of this issue:
```
; Ref: https://github.com/sanskrit-lexicon/CORRECTIONS/issues/146
¯A4C2V.GR2HJ.1,7,19.@zawpad@za/wpad@116153:¯A7C2V.GR2HJ.1,7,19.:t:
¯A4RAJABH.2,28.@padI@padI@62833:¯A7RAJABH.2,28.:p:
¯A72V.Grhj.3,7,4.@uttarApara@uttarApara@18249:¯A7C2V.GRHJ.3,7,4.:t:
¯A72V.C2R.9,9,5.@Satapuzkara@Satapuzkara@109854:¯A7C2V.C2R.9,9,5.:t:
¯A7APST.)@rAD@rAD@93808:¯A7PST. ):t:
¯A7APST.C2R.13,24,8.@rAjaMBavya@rAjaMBavya@93456:¯A7PST.C2R.13,24,8.:t:
¯A7BJABH.2,10.@vfttapariRAha@vfttapariRAha@106387:¯A7RJABH.2,10.:t:
¯A7BJABH.2,2.@vfnda@vfnda/@106634:¯A7RJABH.2,2.:t:
¯A7BJAV.78,7)@tripurAntaka@tripurAntaka/@47602:¯A7RJAV.78,7 ):t:
¯A7BSH ‹BR.›@yama@yama/@90248:¯A7RSH.BR.:t:
¯A7C2.@kar@kar@24527:¯KA7C2.:t:
¯A7C2A.C2R.1,2,16.@svavargya@svavargya@132770:¯A7C2VA.C2R.1,2,16.:t:
¯A7C2B, ¯GR2HJ.3,6,7.@dakzakratu@dakzakratu/@48397:¯A7C2V.GR2HJ.3,6,7.:t:
¯A7C2BV.C2R.3,1,14.@saMmahas@saMmahas@121231:¯A7C2V.C2R.3,1,14.:t:
¯A7C2V.C2R.8,13,35.Man ‹könnte@paScAttara@paScAttara@65235:¯A7C2V.C2R.8,13,35. ‹Man könnte:t:
¯A7C2V.GR2HJ.AS.1,23,20.@anudeSin@anudeSin@4453:¯A7C2V.GR2HJ.1,23,20.:p: GR2HJAS is elsewhere GR2HJ.
¯A7G4AN.19,43.@kukkuvAc@*kukkuvAc@28183:¯RA7G4AN.19,43.:t:
¯A7G4AN.7,49.@rasona@rasona@93093:¯RA7G4AN.7,49.:t:
¯A7G4AN.19,133.@likza@likza@96177:¯RA7G4AN.19,133.:t:

```

**Comment by funderburkjim** [comment]
### standard format for literary source changes

This format is an amalgam of 
* the format of [abbrvlist.txt](https://github.com/sanskrit-lexicon/PWK/blob/master/pw_ls/pw_dhaval/abbrvwork/abbrvoutput/abbrvlist.txt) in the PWK repository
* the format of headword corrections described at #154 

There are four colon-separated fields in each line of change.txt
1. an input line from abbrvlist.txt, with the modification of putting the macron character `¯` as the first character.  This is because the macron is used in pw.txt to identify literary sources.
2. The 'new literary source' (copied and modified from field 1)
3. Correction code  (p, t, n) with the same meaning (print error, typo, no change) as in #154 
4. comment field

The first field is copied from abbrvlist.txt, and then the macron prepended.
It also consists of several fields, separated by the '@' character:
1. The literary source field.
2. key1 form of headword
3. key2 form of headword  (this field is not used by generate.py)
4. the 'L' number  (record number within pw.xml)

This form is quite flexible for submitting corrections.  For instance, consider this record from
change.txt above:
```
¯A7BSH ‹BR.›@yama@yama/@90248:¯A7RSH.BR.:t:
```
This was derived from the following record of abbrvlist.txt
```
A7BSH.@yama@yama/@90248
```
When the underlying record in pw.txt was consulted, during the construction of change.txt,  it was
noticed that not only was the 'B' in A7BSH wrong (should be R), but also that the second part BR. had been mistakenly written outside the scope of the literary source reference.  The format 
permitted the complete correction as shown.

The reason for making this composite form as just described was so that change records can 
easily be constructed by copy/pasting from abbrvlist.txt.  I am hopeful that this format will facilitate the submission of further corrections to the literary source abbreviations.
