### ISSUE TITLE
blank entry in sanhw1.txt

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#176]
`:ACC,PUI`

There can not be empty headwords.

**Comment by gasyoun** [comment]
It's a visarga, no?

**Comment by funderburkjim** [comment]
The `:ACC,PUI`  indicates an empty headword  (the `:`  in this case is a field-separator in sanhw1.txt).

The problems can be identified by searching for '::' in acchw2.txt and puihw2.txt, respectively.

In ACC, there are two problems.

![image](https://cloud.githubusercontent.com/assets/6393033/11543612/a30a3794-990b-11e5-92e9-e71d7792b0a7.png)

As indicated, the blank headword in digitization should be SANKAyana.
Also, the digitized spelling of first headword is SANKyamitri which should be SANKamitri .

These corrections will get rid of the empty headword in ACC.

As to PUI, the blank headword occurs after kUwaka:

![image](https://cloud.githubusercontent.com/assets/6393033/11543786/8e4fc246-990c-11e5-89dc-27bb45b030d0.png)

So the blank headword should be 
kUwakambalamansIyas  or maybe it is ...zIyas (since there may be a dot under that 's').

This compound would probably parse, in part, as 'kUwa-kambala'    But there I am stuck.

@drdhaval2785 , @zaaf2   Help!

When that detail for PUI is straightened, I'll make the corrections to ACC, PUI.

**Comment by funderburkjim** [comment]
acc corrections installed.

**Comment by zaaf2** [comment]
@funderburkjim Re `kUwakambalamansIyas or maybe it is ...zIyas`

There are various reading of the quoted passage (Vāyu Purāṇa 44.10), but there is no doubt that the sibilant in question is ष् (`kUwakambalamanzIyas`):

[Vāyu Purāṇa 44.10](http://dli.serc.iisc.ernet.in:8080/handle/2015/553740) (PDF pg. 359):

![image](https://cloud.githubusercontent.com/assets/14730665/11554367/25048ece-9976-11e5-8200-b02f2f762281.png)


[Translation](http://dli.serc.iisc.ernet.in:8080/handle/2015/274476) (PDF pg. 349):
![image](https://cloud.githubusercontent.com/assets/14730665/11554348/ee4948e8-9975-11e5-8ece-21e4cfe77757.png)

**Comment by gasyoun** [comment]
seems that the ending 's' is an English pluralization - it is indeed.

**Comment by funderburkjim** [comment]
Correction to PUI Installed.
