### ISSUE TITLE
Abnormal endings

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#177]
CCS:SanEm:SanEs:p:Only word ending with Em in sanhw1
![capture](https://cloud.githubusercontent.com/assets/5755132/11505348/f89bb1c0-986f-11e5-8dfe-a2db662150c2.png)

**Comment by gasyoun** [comment]
So you gather stats on what letters words end?

**Comment by drdhaval2785** [comment]
No I don't gather such stats. Just noted because it came up. Otherwise it would have been lost.

**Comment by drdhaval2785** [comment]
ap90:mAhadreM:mAheMdra:t:Wrong placement of e.

![capture](https://cloud.githubusercontent.com/assets/5755132/11507393/d79d1996-9879-11e5-9257-83d1b1fffb79.png)

**Comment by drdhaval2785** [comment]
ap90:ApeH:ApiH:t:

![capture](https://cloud.githubusercontent.com/assets/5755132/11507679/33828a7e-987b-11e5-8b33-865ff12215a0.png)

**Comment by drdhaval2785** [comment]
skd:yavakzodeH:yavakzodaH:t:

![capture](https://cloud.githubusercontent.com/assets/5755132/11507822/d07c6b56-987b-11e5-8538-153178e2816b.png)

**Comment by drdhaval2785** [comment]
This ends correction submission here.

**Comment by gasyoun** [comment]
I guess stats would not hurt.

**Comment by zaaf2** [comment]
Pretty straightforward corrections. :+1:

**Comment by funderburkjim** [comment]
Re CCS:SanEm:SanEs:p:Only word ending with Em in sanhw1

I think you meant 't'  (typo, same as OCR error - a mistake by typist), since this is clearly is a Devanagari 's' in the print, as it should be,  

As I use the abbreviations, 'p' means that the printed text is in error (print error) and that we are making a change.  'p' cases get added to the ccs_printchange.txt file.

Just wanted to be sure we are using the same conventions.

**Comment by drdhaval2785** [comment]
Yes. I meant typo. You are right

**Comment by funderburkjim** [comment]
Corrections installed.
