### ISSUE TITLE
INM retroflex issue

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#205]
Per my comment at https://github.com/sanskrit-lexicon/CORRECTIONS/issues/204#issuecomment-165631156
This is the list of words caught by regex `sh2[tdns][h]*[^2]` in inm.txt
All of them should have a trailing '2' in my opinion

Line 43554: <C1>2. wind {%(ma1ruta).%} <C2>skin {%(tvac)…%} <C3>objects of touch {%(sprash2tavya)…%} <C4>Lightning {%(Vidyut).%}
Line 44734: <>Vasish2tha), 11511 (do.).--§ 717{%b%} (Na1ra1yan2i1ya): XII,
Line 62482: <>as Yudhish2thira had by his ra1jasu1ya).--§ 327 (Draupadi1-
Line 64679: <>the reason of {%Kr2sh2na's%} assuming the form of an animal.
Line 67399: <>caiva Dharmakulodvahau devaçresh2thau);%} {@344,@} 13310
Line 72440: <>{@142,@} 10927 {%(nash2ta1 vasumati1 kr2tsna1 Pºe caiva majjita1).%}--
Line 74248: <>{%(ash2tau),%} 11554 (do.), 12725 ({%sapta,%} i.e. the seven r2shis,
Line 74249: <>Manu is the eighth), 12737 (= do.), 13041 ({%ash2tau,%} i.e. the

**Comment by funderburkjim** [comment]
This is a non-issue. It must have been that my explanation was confusing, since I only showed
the old *uncorrected* lines.

 I think these were already properly corrected under #204.  Here's proof, by listing those lines
after correction.

$ sed -n '43554p;44734p;62482p;64679p;67399p;72440p;74248p;74249p' inm.txt
<C1>2. wind {%(ma1ruta).%} <C2>skin {%(tvac)…%} <C3>objects of touch {%(sprasht2avya)…%} <C4>Lightning {%(Vidyut).%}
<>Vasisht2ha), 11511 (do.).--§ 717{%b%} (Na1ra1yan2i1ya): XII,
<>as Yudhisht2hira had by his ra1jasu1ya).--§ 327 (Draupadi1-
<>the reason of {%Kr2shn2a's%} assuming the form of an animal.
<>caiva Dharmakulodvahau devaçresht2hau);%} {@344,@} 13310
<>{@142,@} 10927 {%(nasht2a1 vasumati1 kr2tsna1 Pºe caiva majjita1).%}--
<>{%(asht2au),%} 11554 (do.), 12725 ({%sapta,%} i.e. the seven r2shis,
<>Manu is the eighth), 12737 (= do.), 13041 ({%asht2au,%} i.e. the

**Comment by drdhaval2785** [comment]
Great. If it is corrected, lovely.
