### ISSUE TITLE
2-grams vs MW72, part 1

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#241]
http://sanskrit-lexicon.github.io/CORRECTIONS/ngram/output/html/allvsMW72_2.html examined here.
Total 54 entries.
Will be handled in single issue.

Update - 
Completed the correction submissions.
https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/ngram/output/corrections/allvsMW72_2_corrected.txt is the corrected file.

**Comment by drdhaval2785** [comment]
1-10
```
acc:aRREyaAcArya,255:aRREyaAcArya:n:RE
acc:aRREyapaRqita,256:aRREyapaRqita:n:RE
pw:atridagja,2351:atridagja:n:gj
pw:anuzwupkArmIRa,4904:anuzwupkArmIRa:n:pk
ccs:arTayvavahAra,1827:arTavyavahAra:t:yv
pw:arDANI,9739:arDANgI:t:NI
acc:azwESvaryaPala,39397:azwESvaryaPala:n:wE
pe:uccESSravas,7650:uccESSravas:n:SS
bop:upaspfrSA,1466:upasparSa:t:fr
inm:etAvarRO,3903:etAvarRO:n:RO
```

**Comment by gasyoun** [comment]
3:10 - true error stats get lower. Still 30% is high enough. Thanks for the efforts in cleaning out the dirt!

**Comment by drdhaval2785** [comment]
I would appreciate if anyone takes over submission job @gasyoun. Not a very
productive work. If someone takes over submission, i can spend some more
time in coding to find out some more methods. Not optimal utilisation of
resources I would say.

**Comment by gasyoun** [comment]
I'm of the same opinion. But there is an issue or rather one byproduct in which I'm more than interested. If the Reverse dictionary should come (and if you accept I would want your name as an editor on it), it will be printed in 2 volumes and the first should come out before March. That means even if there will be developed better methods, they will require realization that will not be possible, because as of now we are how many we are. And I do try to find help. Right now I'm making tutorials for my Sanskrit class and hope at least 3 out of 9 pupils will be able to submit simpler mistakes.
Other thing was I think we should kill `ccs` issues before in some other `ccs` centered round, otherwise there could be more of them, than they actually deserve to. The "main" dictionaries remain PWG, PWK, SCH, MW and AP. And https://github.com/drdhaval2785/samasasplitter will be one of the most practical additions for the purely sanhw1.txt based headword list as of now. Thanks and let's do our best - if not always the optimal way, still the carriage moves on. But I do agree and I'm letting you know that almost every two weeks I try to find people who will have at least some time on a regular basis to help.

**Comment by funderburkjim** [comment]
> bop:upaspfrSA,1466:upasparSa:t:fr

Agree.  Also noticed the two previous words need correction.

```
bop:upasAna,1464:upasTAna:t: paper wrinkle in scan
bop:upasita,1465:upasTita:t: paper wrinkle in scan
```
![image](https://cloud.githubusercontent.com/assets/6393033/12494046/2bfeb018-c056-11e5-83f7-2abce2e627bf.png)

**Comment by funderburkjim** [comment]
Corrections installed

**Comment by drdhaval2785** [comment]
This deserves reopening, since only 10 /54 were examined.
The rest need correction.
Reopening, lest they be lost.

**Comment by gasyoun** [comment]
After March, @drdhaval2785 ?

**Comment by drdhaval2785** [comment]
@funderburkjim and @gasyoun, I would be away fr quite some time. In the interim, I would suggest that we take up bigrams testing as per order mentioned in https://github.com/sanskrit-lexicon/CORRECTIONS/issues/185. Right now we are on MW72. At least bigram testing would be highly beneficial.

**Comment by gasyoun** [comment]
@drdhaval2785 what bigrams have been done? Can you mark them?

**Comment by drdhaval2785** [comment]
MW, PW, PWG, PD
allvsMW...... allvsPD

**Comment by drdhaval2785** [comment]
11-20
```
vcp:kapikacCUPalopamA,11844:kapikacCUPalopamA:n:UP
inm:kirIwaBfw,5768:kirIwaBft:t:fw
yat:KawKawati,12055:Kaw:t:wK
inm:guROzada,4297:guROzada:n:RO
acc:gopIjanavallaBacaraREkatAna,32706:gopIjanavallaBacaraREkatAna:n:RE
acc:gOrANgasmaraREkadaSaka,6668:gOrANgasmaraREkadaSaka:n:RE
mw:pallISarawayoHPalAPalavicAra,120295.1:pallISarawa:t:oH
mw:pallISarawayoHSAnti,120295.2:pallISarawa:t:oH
pwg:pANI,78382:pANI:n:NI
mw:pARO,121515:pARO:n:RO
```

**Comment by drdhaval2785** [comment]
21-30
```
bhs:pArTagjanaka,9464:pArTagjanaka:n:gj
bhs:prajYopaka,9909:prajYopaka:n:Yo
vcp:praRANI,33608:praRAqI:t:NI
inm:prAgjyotizADipa,8478:prAgjyotizADipa:n:gj
acc:brahmasUtrazawSAntiprakaraRa,35108:brahmasUtrazawSAntiprakaraRa:n:wS
ben:Bipagjita,10591:Bizagjita:t:gj
acc:muhUrtacintAmaRO,35814:muhUrtacintAmaRO:n:RO
acc:yajYopanizad,45817:yajYopanizad:n:Yo
acc:yajYopavItaDAraRaviDi,35910:yajYopavItaDAraRaviDi:n:Yo
acc:yajYopavItanityaDAraRaviDi,45818:yajYopavItanityaDAraRaviDi:n:Yo
```

**Comment by drdhaval2785** [comment]
31-40
```
ccs:yajYoyavIta,19483:yajYoyavIta:n:Yo
pui:yazwikfw,11263:yazwikfw:n:fw
bhs:yvAgU,12524:yvAgU:n:yv
inm:rAmAyaROpAKyAna,8984:rAmAyaRaupAKyAna:t:RO
pui:rudrakarRO,11697:rudrakarRO:n:RO
bhs:vAyvADika,13522:vAyvADika:n:yv
acc:vAsoyajYopavItasaYcikA,36901:vAsoyajYopavItasaYcikA:n:Yo
inm:SAntanoHputra,2437:SAntanoHputra:n:oH
ccs:SiMSSa,24536:SiMSa:t:SS
mw:SirorogaGnayajYopavItadAna,217209:SirorogaGnayajYopavItadAna:n:Yo
```

**Comment by drdhaval2785** [comment]
41-50
```
acc:SirorogaGnayajYopavIvadAna,25053:SirorogaGnayajYopavIvadAna:n:Yo
acc:zawKaRqivedAntasAra,47468:zawKaRqivedAntasAra:n:wK
sch:zawtarkIrasa,25454:zawtarkIrasa:n:wt
skd:zawtilI,36937:zawtilI:n:wt
mw:zawtriMSan,225001:zawtriMSan:n:wt
cae:zawtriMSAbdika,33639:zawtriMSAbdika:n:wt
bhs:saMjYotpAda,15654:saMjYotpAda:n:Yo
pw:saMjYopasarjanI,117984:saMjYopasarjanI:n:Yo
inm:sadasatoHpara,9209:sadasatoHpara:n:oH
acc:saPalAkfzROkAdaSIpOzI,47656:saPalAkfzREkAdaSIpOzI:t:RO
```

**Comment by drdhaval2785** [comment]
@funderburkjim This item on radar?
