### ISSUE TITLE
The word NORM

### ISSUE THREAD

**Issue by prasaadu** [sanskrit-lexicon/CORRECTIONS#258]
One of the meanings turned out is यथाकमं. It should be यथाक्रमं

**Comment by gasyoun** [comment]
In what dictionary?

**Comment by prasaadu** [comment]
Apte English Sanskrit Dictionary Query, 2007

**Comment by prasaadu** [comment]
Norm, (p. 309)

**Comment by prasaadu** [comment]
Apte English Sanskrit Dictionary Query, 2007
Norm, (p. 309
<http://www.sanskrit-lexicon.uni-koeln.de/cgi-bin/serveimg.pl?file=/scans/AEScan/AEScanjpg/ae0309-nonage.jpg>
)

svasti
Prasad

**Comment by gasyoun** [comment]
Thanks, are you ready to check for errors on a regular basis, Prasad? @drdhaval2785 could compile a list of fishy words for you if we ask him kindly.

**Comment by prasaadu** [comment]
I didn't get the import of the second sentence. Pls let me know what is expected of me from dhaval. I am a translator and will be looking up online dictionaries regularly. I will make it a point to bring all bloomers to your notice henceforth.

**Comment by gasyoun** [comment]
@prasaadu - are you ready to check a list of possible bloomers? Bloomers only, no normal words.

**Comment by prasaadu** [comment]
Let's give it a start. Tell me how to go about it.

svasti
Prasad

**Comment by prasaadu** [comment]
[image: Inline image 1]
Under ROMANTIC: अभुत incorrect. It should be अद्भुत (as in p.401)

svasti
Prasad

**Comment by drdhaval2785** [comment]
@prasaadu 
Just to get you started in correction submissions, Please have a look at http://sanskrit-lexicon.github.io/CORRECTIONS/ngram/output/html/allvsVCP_2.html.
We have highlighted the sequence which we find fishy in yellow colour.
The HTML file has link to the digital data as well as scanned images for confirmation.
Please have a look at the words and whenever it needs correction, please post it in https://github.com/sanskrit-lexicon/CORRECTIONS/issues/257.
I have already examined 10 entries.

As you are new to the process, you need not worry about the format in which the correction is submitted. We would encourage you to use [slp1](https://en.wikipedia.org/wiki/SLP1) encoding.

N.B. - If you want to submit in a more easily machine readable format, please read [this](https://github.com/sanskrit-lexicon/CORRECTIONS/issues/154). This is the format in which I have submitted the 10 corrections.

**Comment by gasyoun** [comment]
@drdhaval2785 I guess @prasaadu  was interested in English-Sanskrit dictionaries first.

**Comment by prasaadu** [comment]
No such proclivity Marcis. I will go through this soon.

svasti
Prasad

**Comment by gasyoun** [comment]
The better.

**Comment by prasaadu** [comment]
I went through
http://sanskrit-lexicon.github.io/CORRECTIONS/ngram/output/html/allvsVCP_2.html
.
I am not sure what I have to do there and how. I am sorry I haven't the
patience to go through the lengthy instructions. I feel the need to be
oriented. So, I will stick to my current method. Whenever I find a bloomer,
I will bring it to your notice.
Shreevathsa is a friend of mine who can be of great value to you. He is
young, very proficient in Sanskrit and is tech savvy. He is approachable. I
have copied this to him. Please correspond with him. Possibly I will take
this up if he too does, and later orients me.
svasti
Prasad

**Comment by shreevatsa** [comment]
I was cc-ed on this and I don't understand what all this confusion is. This is what I understand:

- @prasaadu wants to contribute corrections in Apte English–Sanskrit Dictionary, as and when he encounters them.
- So far he has found two: (1) under the headword "norm", the Sanskrit word digitized as यथाकमं should be यथाक्रमं, and (2) under headword "romantic", the word अभुत should be अद्भुत.
- Is creating an issue in this repository the right way to submit such error reports or not? I don't think the url http://sanskrit-lexicon.github.io/CORRECTIONS/ngram/output/html/allvsVCP_2.html or the bug #257  has anything to do with it; it is a list of suspicious things for someone to look at, but I don't think @prasaadu is interested in pursuing that project; all he wants is to submit corrections when he encounters them in the normal course of looking up words in the dictionary. What is the best way for him to submit corrections?

**Comment by drdhaval2785** [comment]
It is absolutely fine if @prasaadu submits his corrections the way he is
doing right now.
If he wants to help clean up the dictionary systematically, he is welcome
to pursue the links given.
Otherwise no need to open them.

**Comment by prasaadu** [comment]
Sorry Dr. Dhaval Patel,
I am interested if it is quite simple. I am 57 and complex processes make
me easily susceptible to fatigue :( I will find out from Shreevathsa if I
can really do this, and will then revert to you. Pls bear with me.
svasti
Prasad

**Comment by funderburkjim** [comment]
@prasaadu . Hi!

Most of our error detection work so far has been focused on the headwords of Sanskrit-English, Sanskrit-German, etc. dictionaries.  And we've developed some workflows which are geared towards
making that work efficicient *once you get used to it* -- But, I agree that they would seem complex to
someone not involved in the development of the procedures.

A year or so ago, one of our contributors, @Shalu411 , began looking at the errors in Apte English-Sanskrit dictionary, and found many errors in the first few pages of that dictionary in the spelling of the Sanskrit words which appear in the definitions of the English words -- the kind of situation you pointed out above with यथाक्रमं under headword 'norm'.

While working on this, we tried one thing as an attempt to make it easier for Shalu to make corrections, namely we put a few pages in a wiki, specifically the one at wikisource.
[Here](https://en.wikisource.org/wiki/Page:Apte_English-Sanskrit_Dictionary_Test.pdf/2) is a
link to one of those pages.    The idea was that it might be easier to make changes to the wiki.

This is just an example; it may or may not be the best way for an interested participant, such as possibly
you are, to make spelling corrections to the dictionary.

Another way would be to prepare a special version of the text file which represents the AE dictionary and allow you to make corrections in this special version with a text editor.   

There are various possibilities.   If you are interested in making a sustained effort to improve the spellings in the AE dictionary,  we can probably work together to develop a procedure which you find
convenient.  Let me know if this is the case.

Otherwise,  if you prefer for now to submit corrections in an informal way, that is also fine, and appreciated.

By the way, you mentioned that you are using [Apte English Sanskrit Dictionary Query, 2007](http://www.sanskrit-lexicon.uni-koeln.de/aequery/index.html) .  
I urge you to use one of the newer displays  for this dictionary -  You can find these via the [Cologne sanskrit lexicon home page](http://www.sanskrit-lexicon.uni-koeln.de/) at 	Apte Student's English-Sanskrit Dictionary, or directly from this list of displays [here](http://www.sanskrit-lexicon.uni-koeln.de/scans/AEScan/2014/web/index.php).   The main reason you should use one of these newer displays is that the corrections (such as the यथाक्रमं  one) will NOT be made to the old 2007 dictionary, but WILL be made (though I have not yet installed this correction) to the newer displays.

**Comment by gasyoun** [comment]
@funderburkjim now you see how many people still use the `2007` versions :vhs:

**Comment by prasaadu** [comment]
Dear funderburkjim,
Thanks for taking pains to clarify. I will acclimatize myself with the
procedures and revert to you shortly.
svasti
Prasad

**Comment by drdhaval2785** [comment]
Time to close.
Prasaadu may give occassional inputs for corrections.
