### ISSUE TITLE
AP90 v. AP: headwords

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#332]
It was noticed during the study of 2-grams for AP90  (see #329) that there is a high degree of correspondence between the AP90 and AP dictionaries.   It might be possible to leverage this correspondence to weed out the large number of 3-gram instances of AP90, to get a more feasible number of cases to examine individually by the UI.

As preparation for this,  it seems reasonable to first do a comparison on the headword spellings of the two dictionaries.  
Although the aim of this comparison was not to find headword spelling errors, early work suggests that we will in fact find numerous spelling errors in headwords in the two dictionaries.  

It is desirable to make these corrections first, before proceeding with the comparison of Sanskrit snippets between the two dictionaries.

**Comment by funderburkjim** [comment]
## Gross comparison of headword lists

Based on the current Cologne digitizations, here are some statistics and observations regarding headwords:

* Number of headwords, including duplicates:
  * AP90 has 32034 headwords
  * AP  has    36704 headwords  
  * AP has 4670 more headwords
* Unique headwords
  *  1115 headwords in ap90 but not ap
  *  6031 headwords in ap but not ap90
  *  4916 more distinct headwords in ap than ap90
* Headwords appearing more than once:
  * AP90 has 564 repeated headwords
  * AP has 731 repeated headwords
* The spelling of headwords in AP normally uses homorganic nasals, while that in AP90 uses anusvAra.
* Both dictionaries usually use nominative singular for nouns.
   * AP90 spells neuter nouns in 'a' with an ending 'aM'.
   * AP spells these with an ending 'am'

**Comment by funderburkjim** [comment]
## A merged listing of headwords.

The two headword lists not only contain mostly the same headwords.

The order of these headwords is also almost the same.

Thus, it is plausible to use a 'diff' type analysis in order to arrive at a merged list.

The Python difflib.SequenceMatcher  class makes a plausible [merged list](https://gist.github.com/funderburkjim/cfe200a72c9e83e706c9caede10c6ff5).


This merged list is presented in 37061 lines.

Each line has three fields; the fields are delimited by space character: 
* A normalized spelling of the headword
* The AP90 spelling of the headword
* The AP spelling of the headword.

However, some lines have special forms.  These forms are based on the comparison results of the SequenceMatcher.  The SequenceMatcher is told to compare the two lists of **normalized** headwords.
This normalization is based upon that used in the 'hwnorm1' normalization, with a slight adjustment, currently just for ending M or m.

The SequenceMatcher is a very general purpose matcher of sequences of strings.  Based on its way of matching, the lines of our output are essentially of 4 forms:

* **Non-matches** 6658 of these.  regex = `(NO-AP90)\|(NO-AP)\|([?])`
* **NO-AP90** Exact match  30403 of these  .  These need no further examination.

The Non-matches can be further subdivided:
* **Difficult** (search for '?' character). 1668 of these  
   * These may or may not have NO-AP90 or NO-AP
   * **These are  where spelling errors are most likely to be found**
* The Non-matches not marked as Difficult.  There are the non-matches with no question mark,
   * NO-AP90   not in ap90 list
   * NO-AP  not in ap list

If you search within the file for the Difficult cases  ('?'), you'll see many cases where there is a 
probable spelling error in one or the other dictionaries.
However, there are some difficulties in interpreting these cases.
For instance, compare lines 594 and 597:
```
594:?6?atikrUra atikrUra NO-AP
597:?8?atikUra NO-AP90 atikUra
```
It seems almost certain that this is a spelling error of AP, but 

As another difficulty:
```
aG NO-AP90 aG
aGa aGa aGa
?1?aGa,aGana aGa aGana
```
This is resolved by the fact that in AP90, there are two 'aGa' entries; but the first one is 
mis-spelled (the correction should be 'aG', a verb.

Thus, the next order of business is to better understand the *DIfficult* cases and make the
appropriate corrections to the two dictionaries.

**Comment by drdhaval2785** [comment]
Good work Jim.
This issue opens up possibility of examination of various such highly
alligned dictionaries like PWG-PW or WIL-YATES, MW72-MW.
Principles will remain the same with minor changes.

**Comment by gasyoun** [comment]
> This is resolved by the fact that in AP90, there are two 'aGa' entries; but the first one is
mis-spelled (the correction should be 'aG', a verb.

That's why I first work with longer words, because shorter contain more false positives.

> This issue opens up possibility of examination of various such highly
alligned dictionaries like PWG-PW or WIL-YATES, MW72-MW.

Indeed. It's the last call for the batch headword correction still left.

A few cases. 

> ?1?SilinDra SiliMDraH NO-AP

n = M is a convention, so we can remove the ?, no?

> ?1?sahari sahariH NO-AP

Convention, nothing else, I would say, wrong?

> ?1?kavAri,kavArI kavAri kavArI
Both are identical as in book, so it's a print error, suppose AP90, because same meaning. The problem is it's a RV quote and GRA has `kavAri`. GRA should containt an index of all words from Rigveda right.

kavarI:AP,AP90,BOP,MW,SKD
kavAri:AP90,CAE,GRA,MW,MW72,PW,PWG,VCP

**Comment by gasyoun** [comment]
What if check sanhw1 file if "pair" dictionary abbreviations for similar looking words are listed on different lines, like in this kUpinI vs. kupinI example? Why have we not found it before, looks simple, still I see plenty such cases still around, @funderburkjim

**Comment by funderburkjim** [comment]
Am doing exactly that, except using hwnorm1 to take different nasalizations into account.

Stay tuned for a UI, first for the ap90 cases (about 300).

**Comment by funderburkjim** [comment]
Here are UI URLS for 275 ap90 possible headword spelling errors.

[batch 200](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/200/update.php)  [batch 201](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/201/update.php)  [batch 202](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/202/update.php)  [batch 203](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/203/update.php)  [batch 204](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/204/update.php)  
[batch 205](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/205/update.php)  [batch 206](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/206/update.php)  [batch 207](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/207/update.php)  [batch 208](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/208/update.php)  [batch 209](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/209/update.php)  

Here are URLS for Devanagari version of these batches:
[batch 200](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/200/update.php?input=deva),  [batch 201](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/201/update.php?input=deva),  [batch 202](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/202/update.php?input=deva),  [batch 203](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/203/update.php?input=deva),  [batch 204](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/204/update.php?input=deva),  
[batch 205](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/205/update.php?input=deva),  [batch 206](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/206/update.php?input=deva),  [batch 207](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/207/update.php?input=deva),  [batch 208](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/208/update.php?input=deva),  [batch 209](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/209/update.php?input=deva),

**Comment by funderburkjim** [comment]
## Progress Table for 2-gram Batches

The idea is to 'check out' a batch  (enter user name and date begin) when you start a batch.
Then, when you've finished,  again edit this comment and enter date end.

When I install batches, I'll fill in the date for last Installed field.

Batch | case1-case2 | User | Date Begin | Date End | Installed
----- | ----------- | ---- | ---------- | -------- | ---------
200 | 1-5 | @funderburkjim|  01/03/2017| 01/03/2017 |
201 | 6-30 | | | |
202 | 31-60 | | | |
203 | 61-90 | | | |
204 | 91-120 | | | |
205 | 121-150 | | | |
206 | 151-180 | | | |
207 | 181-210 | | | |
208 | 211-140 | | | |
209 | 241-275 | | | |

**Comment by funderburkjim** [comment]
## Help document for the corrections

[analysis1_ap90.txt](https://gist.github.com/funderburkjim/f71106a252ec3385dc7dfc575008e939#file-analysis1_ap90-txt)  should prove useful when working through the UI.

* The records are in the same order as in the batches.
* There is a record for each case.
* The record for a case shows:
  * ap90 first line of digitization
  * ap first line of digitization
  * list of dictionaries with ap90 spelling  (up to normalization)
    * In this group, only ap90 has the given spelling --- that's part of the way the group of 275 was
       chosen
  * list of dictionaries with ap spelling.
     * by construction of this list,  there will always be at least one other dictionary besides ap in this list

**Comment by drdhaval2785** [comment]
Can we have details of corresponding AP entry in UI itself please?

**Comment by funderburkjim** [comment]
* AP entry now shown in UI  (derived from the Help document)
* auto-incrementing to next case upon submit .

@drdhaval2785  Enjoy :)

**Comment by gasyoun** [comment]
![devava](https://cloud.githubusercontent.com/assets/80761/21636680/a70a2806-d274-11e6-9926-8bf8e62ae8a6.PNG)

Jim, UI is much better, still after working for a few hours with finding the typoes, here is what I miss:
1) Having twice the same does not make sense, when at the same time I would want to see AP90 vs. AP, can we have it in the list?
1. अनाहरिन्  (अनाहरिन्)
2. अनप्रश्नः  (अनप्रश्नः)
3. अपाचित्  (अपाचित्)

2) ?1?kadAra,kEdAra kadAra kEdAra provides me some meta data. All the cases in UI are the ? ones, right? But not all ? are equal and so the priority of browsing through them.

> ?1?kElAsa kElAsaH NO-AP
?1a?kElAtakam NO-AP90 kElAtakam
?2?kElasa NO-AP90 kElasaH

Cases are not equal with

> ?1?koRAkoRi,koRAkoRI koRAkoRi koRAkoRI

Without that splitting 1600 cases is a lot, am I wrong, @drdhaval2785 ?

3) amAMsa:AP,MW,MW72,PW,PWG,SCH,SHS,VCP,WIL,YAT can we have the abbreviations clickable in case I need to see what's there? When there are 20 vs 1 I go for 20 not even opening, but when there is only 1 case I would rather want to see it.

4) From `AP90 headwords (instance)` I can click on AP90 only, the AP is non-clickable, right? That makes the UI similar to .txt, not that much value added as I would want to. Hope it's not that hard to implement, because AP90 vs AP is not the only pair and it's the top 5 dictionaries used widely nowadays.

**Comment by funderburkjim** [comment]
@gasyoun  Regarding UI changes -  Some of your suggestions are plausible, but since you are not actively participating in submitting corrections via the UI, I am less inclined to spend time implementing them.  It seems reasonable to give more weight to suggestions from actual users.   Nevertheless, the observation, esp. regarding links for the dictionary list, might prove to have practical value , and I'll keep it in mind and maybe implement later.

**Comment by funderburkjim** [comment]
> Without that splitting 1600 cases is a lot,

I absolutely agree.  Here's my informal strategy for dealing with these cases.
* Deal with the almost sure AP90 errors -- That's the list of 275 mentioned with the batches above.
* Generate UI for a similar number (300) of almost sure AP errors -
* Redo the whole matching logic in light of the 600 or so corrections.
* Re-examine the list of '?' , especially with an eye to white-listing.

**Comment by gasyoun** [comment]
> since you are not actively participating in submitting corrections via the UI

You never know ahead. As it's headword related I'm in. But after experimenting with the .txt I wish for what I have documented and hope I'm not the only one.

**Comment by SergeA** [comment]
In the batch 202, the case 6 is duplicated by the case 7. And a wrong line is highlighted in the last.
The same is for 14 & 15.

@funderburkjim Can we have an option of auto-opening of the scan page when a case is loading in the window? (And also a switch for turning this option off when not needed.)

**Comment by SergeA** [comment]
Some cases of different spellings are hard to decide.

> Case 9: hw=इलीविषः DONE (इलीविषः → इलीबिशः)

N. of a demon
MW,MW72,PW,PWG &c. have इलीबिशः.
ब/व & श/ष can be variations of spelling.
Changed only because in AP1957 there is quotation from RV with this name.

> Case 10: hw=इलीषः DONE (इलीषः is spelled correctly)

A sort of fish
While MW,MW72,PW,PWG &c. have इलीशः.
Not changed because we can not know if it was an error or an intentional different spelling. श/ष can be a variational spelling.

**Comment by drdhaval2785** [comment]
Batch 208 done.

**Comment by funderburkjim** [comment]
> Can we have an option of auto-opening of the scan page 

The batches now have a version of this.

The behavior is different, (in my Chrome browser at least) depending on how a new case gets loaded:
* Clicking on one of the words loads the scan page AND switches the Browser to the scan page tab.
* When you click submit, a new case is loaded AND  the scan page loads BUT the Browser does not
   switch focus to the new tab.

The checkbox at the top turns on/off this autoloading behavior.

@SergeA   Does this work for you?

**Comment by funderburkjim** [comment]
> Having twice the same ...

UI changed so that the spelling of the alleged corresponding AP word is shown in parentheses in the word list.

This parenthetical word appears only in SLP1, even when the user is looking at other things in Devanagari. 
It's too complicated to get this word in Devanagari now.

**Comment by funderburkjim** [comment]
There is a [test](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/test/update.php) url

and a [test-deva](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-332/test/update.php?input=deva) url

that you can experiment with.  The results won't be used in installing cases.

**Comment by gasyoun** [comment]
> UI changed so that the spelling of the alleged corresponding AP word is shown in parentheses in the word list.
Thanks.

> It's too complicated to get this word in Devanagari now.
Understood.

> The batches now have a version of this.
Quick one, wah. So you see the scan before you even see the text, interesting one.

**Comment by SergeA** [comment]
>     Clicking on one of the words loads the scan page AND switches the Browser to the scan page tab.

Auto switching to the scan-tab is unwanted. Because first we have to read the case.
Fortunately in my FF it switches only when opening this tab for the first time. And then, it reloads the tab without switching. So in FF I've got what I wanted. Thank you! :)
However Chrome switches every time, and it is annoying.

>     When you click submit, a new case is loaded AND the scan page loads BUT the Browser does not
>     switch focus to the new tab.

Did you use different code for this or it depends only of the browser mood? I suppose it uses different procedures. In FF when scan tab is not opened, when clicking on the word it opens a new tab silently, but when submitting it tries to block a pop-up window. And in my Chrome when scan tab is not opened, when clicking on the word it opens the tab, but when submitting it does not open without saying anything (suppose the pop-up window is auto-blocked).

> The checkbox at the top turns on/off this autoloading behavior.

Good!
And can we have similar checkbox for the auto-continuing on/off? I've get accustomed to click manually, so I automatically click, and then it switches further , and this is a bit confusing. It is not a big problem, but I feel more comfortable without this option. Also some hard cases require additional reflection even after submitting. But when there are many simple cases auto-continuing is good.

**Comment by drdhaval2785** [comment]
Autoswitch to scan is definitely an overkill. Reading case first is
necessary.

**Comment by SergeA** [comment]
> Autoswitch to scan is definitely an overkill. Reading case first is necessary.

Yes. The problem with showing scan first ought to be solved somehow.
Perhaps it is better to turn this checkbox off by default.
But with my Firefox today it works fine. And I'm happy to have this functionality. It allows to concentrate on correction and not on clicking.

Another suggestion to improve the usability of the UI is to add buttons "previous" and "next" to have the possibility to quickly look through all cases.

**Comment by funderburkjim** [comment]
> the problem with showing scan first ought to be solved somehow

This is a technical problem that I don't know how to control.   Stack overflow discusses such things, but I've not found a solution thus far.  I haven't tested with FF, but from SergeA's remarks, it seems that the behavior of the UI differs between FF and Chrome.  

From SergeA's comment `So in FF I've got what I wanted`, I conclude that the system is currently usable
for others.

Thus, I'm going to impose a moratorium on further changes to UI now ---  the UI wish list is endless, it seems! I think the UI is usable in current form, and that's the objective.   

Will keep other suggestions in mind when writing the UI for the next phase (AP likely headword errors).

**Comment by funderburkjim** [comment]
After working through batch 201, I found the scan autoload and the case auto-increment features helpful.  Also, having the AP item in the word list helped focus attention to the problem area of a case.

So,  Thanks for all good suggestions.   

Batch of 25 took only 20-30 minutes.

I wonder if Cortana can learn to switch browser tabs?

**Comment by funderburkjim** [comment]
Worked through batch 207 with Firefox.  UI seemed to work similarly to Chrome; but was slightly better,
in that when clicking on a word, the focus was NOT switched to the scan-tab EXCEPT FOR THE FIRST TIME.

One detail is that is worse in FF is that the 'Comment box' sizing is wrong.
FF:
![image](https://cloud.githubusercontent.com/assets/6393033/21733952/00ab7020-d42f-11e6-9138-4c506973332d.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/6393033/21733985/207fce1e-d42f-11e6-8afa-52ac7271dd24.png)

This is probably due to something with CSS - Maybe I'm doing something non-standard which Chrome is fixing --- Any ideas what to look for?

**Comment by SergeA** [comment]
> One detail is that is worse in FF is that the 'Comment box' sizing is wrong.

The comment box changes its proportions when zooming in/out. With smaller fontsize it gets worse, with bigger better. In Chrome there is the same problem, though less noticeable.

**Comment by funderburkjim** [comment]
All the batches have been finished (see progress table above), so installation begins.

The notes marked **?** need review by others.

Notes:
* **?** batch 202, case 10.  Revised to use इलीशः  (print error). Reasons: 
  * many other dictionaries have the palatal sibilant.
  * AP90 shows an alternate spelling, which also uses palatal sibilant:  इल्लिशः
  * The print error will be documented in the ap90_printchange.txt file
* **?** batch 203, case 11.  @SergeA Why did you conclude that गिलयुः should remain and is not a print error,   despite the fact that other dictionaries have गिलायुः  ?
* batch 203, case 31  तृंढ .  This case seems complicated to me.
  * @SergeA  solution is to leave AP90 spelling unchanged, referencing the spelling तृण्ढ  in AP print .
  * Also, both AP90 and AP show this word following root तृंह् , which confirms the nasal.
  * Cologne digitization of AP has spelling तृढ , not in conformity with the text of AP.  
  * All other dictionaries have entry without the nasal.  
  * In AP and AP90, the entry for तृण्ढ and तृंढ both refer to root तृह् (no nasal, and within the body of
    that entry we see the non-nasal form तृढ !
  * It seems that the two AP dictionaries purposely chose to have the entry with the nasal.
  * This is in agreement with @SergeA's conclusion.
  * **A spelling change for AP  (तृढ -> तृण्ढ)  will be generated.**
  * How can our search engines know that तृढ is mentioned in AP/AP90, but under तृह् ? 
* batch 204, case 9.  नरंधि**पः**  or नरंधि**षः** ?  @SergeA mentions finding the पः spelling also in 
   Apte 1965 -- a good reason to leave this spelling in AP90.  We may need a list of cases
   where AP and AP90 disagreements are accepted as valid.  
   * BTW: is there an online source for Apte 1965?
* batch 204, case 13.  Requires AP correction from निर्मूल  to निर्मूल्  .
* **?** batch 208, case 5.  विलुपकः -> ? विलुंपकः  .   I think the change should be made.
  * it would still be in the funky alphabetical ordering of Apte, since part of the sublist
     विलुप् विलुप्त विलुंपकः (  anusvara == dental 'm' here) विलोपः विलोपनं .
  * AP gives quote from Bhagavata Purana with 'लुम्पक'   and this spelling confirmed [here](http://sanskritdocuments.org/doc_purana/bhagpur.pdf), page 53:
   ![image](https://cloud.githubusercontent.com/assets/6393033/21830035/11e8381e-d768-11e6-8aff-5a7a0d690218.png)
* **?** batch 209, case 13 : संस्फलः -> संस्फालः    I think it should be changed to long A (print error)
   * several other dictionaries have the long A
   * In MW advanced search, 3 other words end in long A form: आ- , कर्णा- , वि- .   None end स्फल .
   * causal of स्फल्  has long A.

**Comment by funderburkjim** [comment]
All the corrections have now been processed, but not finally installed.  

I'll see if any comments on the **?**  notes require revision , then finish installation tomorrow.

**Comment by gasyoun** [comment]
> How can our search engines know that तृढ is mentioned in AP/AP90, but under तृह् ?

No way, I guess.

> Apte 1965
The Practical Sanskrit-English Dictionary / Apte V.Sh. 1965 ?

**Comment by SergeA** [comment]
> ? batch 203, case 11. @SergeA Why did you conclude that गिलयुः should remain and is not a print error, despite the fact that other dictionaries have गिलायुः ?

I'll explain my views.
How we can prove a case to be a print error? We have to find some proofs. If it is a misspelled well known word, if in the examples we see the right spelling, if we see it by alphabetical order, if we compare with the spellings of the same word with/without prefix, and if we can check the spelling by a good printed source. The last one is to be used with caution, because different editions can give different readings. As also the manuscripts give many different spellings. The correct spelling can be chosen on the basis of etymology or comparative linguistics etc., but these methods are not omnipotent, and in some cases even the most prominent scholars can not say which spelling is correct. And I think it is not our task to judge these questions. When the text or the context of the dictionary does not show the word as an error then we should not correct the spellings. We do not know, what was in author's head, what was his intention, what was his reason for that spelling.

When I see Apte's spelling is different from all the others' but when there are no other arguments, then I say -- yes, it is suspicious, but we can not say here for sure who's right and who's wrong. When MW agrees in spelling with PWG - who knows, perhaps he just copy-pasted this spelling. When AP(1957) agrees with both MW and PWG - who knows, perhaps those editors Gode and Karve just corrected all the Apte's spellings after MW without any additional research. But how we can say Apte did not have another manuscript with another spelling of the word? We do not know, if there were some reasons for those spellings or not. Perhaps it was an error in Apte's dic, but perhaps Apte is right and all the other copy-pasted a wrong spelling. So I do not count the difference of spelling as enough reason for correcting Apte's readings.

Also, look at MW. There are many words there marked as "wrong reading for..." Monier does not reject those wrong spelling but includes them in the word-list. So we should not reject Apte's spellings only on the ground of being different. Even if they are wrong they are still reading variants.

Also, I have on my bookshelf a reprint of the 4th edition (1965), where the obvious print errors (as omissions of viramas etc.) are corrected, but most Apte's original spellings (as far as I compared them) are kept untouched. The pages of 1965 ed. differ from 1890. As I found, the text of this 4th ed. is the same with the text of the 3d ed. of 1924. (The ed. of 1965 has an addendum of hundred pages with new words from the books printed by that time. Which shows it was not a blind reprinting of the old edition, but also some research took place there.) In the publishers' note it is said: "This ed. is a reprint of the 2nd revised and enlarged ed. of 1912 which Principal V.S. Apte himself revised." I did not find the 2nd ed. for comparison. And I do not know how could Apte revise that ed. of 1912, when he died soon after the 1st ed., in 1892. Perhaps he left some papers with corrections for the 1st ed. Anyhow there is at list one more revised edition of Apte's dic, which keeps the spelling of 1890. So we should not so easily correct them as print errors.

http://www.dli.ernet.in/handle/2015/14015
3d ed. 1924

https://archive.org/details/practicalsanskri00apteuoft
4th ed. 1965

**Comment by funderburkjim** [comment]
@SergeA   A nice summary of principles.  Worth several readings.

I probably also use another principle, which has something to do with 'utility'.   
In the गिलयुः example it would  be something like this.

* गिलयुः  appears only in AP90.  
 * In the sister dictionary AP(57), at the same point in the two lists of words, we find the spelling गिलायुः 
 * And the two dictionaries have the same English gloss, in this case identical glosses (`A hard tumour in the throat.`.
 * So, we have two printed spellings of the same underlying word.
 * The presence of the AP spelling in other dictionaries makes me think that there must be something wrong with the AP90 spelling.  
* Thus, for utility, the AP90 entry should be associated with the other entries.

Probably there is universal agreement with this last statement.

Then the question is how can we modify our digital information so that the AP90 entry comes up along with the other entries when searches are done.

Currently, the most pragmatic way to accomplish this is to change the spelling of the headword in the AP90 dictionary.  

I can see the point that maybe there are manuscripts out there which have the AP90 spelling, and for some reason AP90 is the only dictionary that reflects that fact.   If this were the case, then, by the current practice of changing the AP90 spelling to agree with the crowd, we would lose the ability to get at the word of that hypothetical manuscript.   

This seems to summarize the danger of my pragmatic approach.

I console myself that this potential danger is recoverable, due to the list of print changes to AP90 that is maintained.   From such a list, a future more comprehensive data structure for the digital form of the dictionaries could be devised.  In this comprehensive approach, there would be maintained within the
digitizations themselves both the printed spellings and our adjustments; and search engines would take into account both such spellings.

**Comment by funderburkjim** [comment]
These corrections now installed.

**Comment by gasyoun** [comment]
> I console myself that this potential danger is recoverable, due to the list of print changes to AP90 that is maintained. 

Indeed, I'm for utility as well. Let science wait, in 200 years there will me a new mainstream.
