### ISSUE TITLE
SCH - Entries missed in conversion from txt to XML

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#346]
First two lines of sch.txt
```
.{#a#}100{#a°#}^2¦ , {%asvaptum%} Ta1n2d2ya-Br. 10 , 4 , 4. [Page001.1] [Schµ1] €1
.{#a#}100{#a#}^4¦ m. º= {%sarvajn5o…'rhan%} , S I , 53 , 3. -- Vis2n2u , H 31 , 9; Va1s. 113 , 1. [Schµ2]* €2
```
Whereas the sch.xml has only one line.
```
<H1><h><key1>a</key1><key2>a</key2><hom>4</hom></h><body>m. º= <i>sarvajn5o…'rhan</i> , S I , 53 , 3. -- Vis2n2u , H 31 , 9; Va1s. 113 , 1. [Schµ2]* €2</body><tail><L>1</L><pc>001-1</pc></tail></H1>
```

The first entry is missing from SCH XML file and subsequent products.

**Comment by drdhaval2785** [comment]
One more observation.
There are more than one entries encoded in one line in rare cases. 
See
```
.{#aka#}100{#aka#}^1¦ 1. Unheil , Ka1s4i1kh. 24 , 17. [Schµ25] |{#aka#} ºAdj. = {%akutsita%} , S II , 236 , 2 (Ko. 14 v.u.). -- {%na1sti…kam2…s4iro…yes2a1m2…te…'ka1h2%} , H 43 , 288; º= {%kut2ilaga1min%} , H 43 , 349. [Schµ26] €5
```

`[Schµ25]` and `[Schµ26]` refer to two separate entries. Currently this feature is not incorporated into XML.

**Comment by gasyoun** [comment]
> The first entry is missing from SCH XML file and subsequent products. 

Great catch.

> There are more than one entries encoded in one line in rare cases. 

Yes, indeed. What I wonder is - if there is 1. aka, why there is no 1. aka and just aka as a different part of speech.

**Comment by funderburkjim** [comment]
> the first entry missing

This is a bug in the first step of the headword detection process (hw0.py).  The program skips several
lines at the beginning of the file, until it runs into the first [Page] reference.  Since this page reference is buried in the line (with the first form of 'a'), it erroneously skips that whole line also.

This would normally be easy to fix.   However, doing the obvious program change would change all the L-numbers of SCH --- which would flow through to sanhw2 having thousands of changes.

I'll try to think of a way to make the correction without changing all the L-numbers.

**Comment by funderburkjim** [comment]
> more than one entries encoded in one line in rare cases

From the example, it may be that such cases are recognized by having more than one instance of
`[SchµXX]` in a line of sch.txt.   If so, there are 366 such cases. 

It further appears that there is a vertical bar which identifies the end of the first part:
```
.{#aka#}100{#aka#}^1¦   ....   [Schµ25] |{#aka#}  ....
```
However, it doesn't appear that we need to say these two parts are separate headword.  They are rather
two aspects (sub-entries) of the same headword.    We could use a '<div>` markup to
identify the sections.  This markup could be used as a basis for an improvement (e.g. line-break) in the displays.

**Comment by funderburkjim** [comment]
### [SchµXX]  markup

The `[SchµXX]` designation was added by Thomas as a sequence number for the 'outdented' (non-indented) lines in the print
![image](https://cloud.githubusercontent.com/assets/6393033/25202780/8b9615d2-2524-11e7-94fd-6c5792e983a1.png)

**Comment by funderburkjim** [comment]
### numbered and un-numbered homophones

The case of 'aka' is an instance of an unnumbered homophone, because (this is speculation) not all the entries start with a number;  namely, the 2nd entry for 'aka' in Sch. does not start with a number.

The case of 'a' is an instance of a numbered homophone.  

The distinction is that the first character of *each* entry is a digit for the numbered homophones.  

In the numbered homophone case,  the numbers refers to the PW homophone number.  The example
of 'a' in PW confirms this:
![image](https://cloud.githubusercontent.com/assets/6393033/25204925/ce3184c2-252d-11e7-8531-f276879afcc0.png)
```

**Comment by funderburkjim** [comment]
### sch.txt coding of numbered and unnumbered homophones

In sch.txt, there are two kinds of homophone coding.   One of them is like 'a', where there is a separate
record for each homophone entry.  The other is like 'aka', where the two homophone entries are coded together in one line of the digitization.

From the examples I've looked at, there seems to be no good reason for the 'aka'-type coding.  I think
it would be better to have separate records of the sch.txt digitization for each homophone entry, 

### recoding implication

The implication for changes to the sch.txt coding would be
* Leave the multiple-record homophone cases unchanged.
  *  The 'a' case diverges from this.  Rather than change all the L-numbers, use L=1 and L=1.1 for the
      two record of 'a'
* Change the single-record homophone cases (like aka) to multiple records, and use decimal numbers
   for the additional L numbers.

The detailed recoding of our prototypical single-record homophone case would look like:
```
current coding all as one line of sch.txt. Our current L-number is L=24
.{#aka#}100{#aka#}^1¦ 1. Unheil , Ka1s4i1kh. 24 , 17. [Schµ25] |{#aka#} ºAdj. = {%akutsita%} , S II , 236 , 2 (Ko. 14 v.u.). -- {%na1sti…kam2…s4iro…yes2a1m2…te…'ka1h2%} , H 43 , 288; º= {%kut2ilaga1min%} , H 43 , 349. [Schµ26] €5

Possible revised coding. Use two lines, breaking at the vertical bar
first record, L=24
.{#aka#}100{#aka#}^1¦ 1. Unheil , Ka1s4i1kh. 24 , 17. [Schµ25] 
second record, L=24.1
.{#aka#}100{#aka#}¦  ºAdj. = {%akutsita%} , S II , 236 , 2 (Ko. 14 v.u.). -- {%na1sti…kam2…s4iro…yes2a1m2…te…'ka1h2%} , H 43 , 288; º= {%kut2ilaga1min%} , H 43 , 349. [Schµ26] €5
```

**Comment by funderburkjim** [comment]
I'll wait for others to comment on this before developing programs to carry out the agenda described above.

**Comment by drdhaval2785** [comment]
I agree with proposed methodology.

**Comment by gasyoun** [comment]
> no good reason for the 'aka'-type coding.

Agree.

> The detailed recoding of our prototypical single-record homophone case would look like:

Perfect, as usual.

**Comment by funderburkjim** [comment]
Thanks for feedback.  I'll get started with implementation.

**Comment by funderburkjim** [comment]
These changes have now been made, and are reflected in the [Basic](http://www.sanskrit-lexicon.uni-koeln.de/scans/SCHScan/2014/web/webtc/indexcaller.php) and related displays.

For comparison with the previous coding, the previous version is still available in [list-02.html](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/list-0.2.html) display.

In addition to the headwords above, some other good headwords to compare are:
* a  (first record now visible)
* ac ( shows presence of `<div>`  in new displays)
* aNku (shows proper placement of º before key2)
* U  - not there in new display  (as mentioned in [another issue](https://github.com/sanskrit-lexicon/Cologne/issues/122#issuecomment-297188063)
* sch contains only modern IAST, no AS coding  (probably not visible in displays)
* L-numbers are the same as before, except for the 350+ new entries involved in splitting the homonyms.

Request others to do some random checking and provide feedback.  When all looks ok, I'll finish
installing.  Meanwhile, I'll work on documenting the changes.

**Comment by gasyoun** [comment]
> ac [Cologne record id=666] [printed page link 010-1] 

I would go for `ac [Cologne record ID=666] [Printed book page 010-1] `

Very well looking.

**Comment by funderburkjim** [comment]
@gasyoun   Thank you for formatting suggestion. It is now implemented for sch.

**Comment by funderburkjim** [comment]
The documentation of changes to sch digitization have been posted as an issue comment in the SCH repository; [here](https://github.com/sanskrit-lexicon/SCH/issues/5).

**Comment by funderburkjim** [comment]
When @drdhaval2785  concurs, I'll go ahead and generate the full installation, including S3 backups and update for list-0.2.html.

**Comment by drdhaval2785** [comment]
I concur.

**Comment by funderburkjim** [comment]
Everything now installed. 

This issue can be closed.

**Comment by gasyoun** [comment]
Hurray!
