### ISSUE TITLE
two small md.txt corrections

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#354]
There are two small corrections, unearthed by comparing the md.txt and md_inverted_from_meta.txt files

1. kroDAlu is a headword but missing markup. See under kroDana.
2. yAva^2 is there, but missing yAva^1. Add 1 after caret.

**Comment by drdhaval2785** [comment]
One more

3. `<H1>{@{#hf#}@}2.¦` -> `<H1>{@{#hf#}@}^2¦`

Caret missing. Extra period.

**Comment by gasyoun** [comment]
Dhaval, I adore your methodology and carefulness.

**Comment by drdhaval2785** [comment]
Corrected in the dev server.
@funderburkjim may check.
I am unable to get access to the dev server frontend on md/web/webtc2/index.php address.
It says access forbidden. For ACC it worked well. 

My local server shows the following new headword 'kroDAlu'.

![capture](https://cloud.githubusercontent.com/assets/5755132/26043874/525ef90c-395e-11e7-9aeb-2a8858e71506.png)

And rest of the two items are incorporated in the md.xml and display locally.

**Comment by drdhaval2785** [comment]
@funderburkjim 
Any luck allowing me access to MD frontend on dev server ?

**Comment by funderburkjim** [comment]
@drdhaval2785   I just noticed your message regarding problem accessing dev server web displays for md.

I also have same problem.

Solution is to change permissions on cologne directory.
```
sudo chmod -R 777 cologne
```
Now web displays available for md.

I did this when only acc was within cologne directory.  But apparently system needs to be reminded
when some new directory comes in, such as md.

There probably is some other way to do this, but for now we need to re-up permissions on cologne 
at each new subdirectory.

**Comment by gasyoun** [comment]
> But apparently system needs to be reminded
when some new directory comes in, such as md.

Unix, baby. That's the way I do myself as well, not a big issue after all.

**Comment by funderburkjim** [comment]
### kroDAlu insertion and L-numbers 

Today I got around to bringing the sanhw1/2 files of CORRECTIONS repository up to date.
Just for fun, I took a look at the changes to sanhw2.txt ... AND IT WAS huge  (I did this before commit,
thankfully).   
Looking at the result of 'git diff sanhw2/sanhw2.txt > temp.txt',  it soon was apparent that most of the
differences were because of an increment of 1 in the L-number of headwords in MD.

Investigation led back to kroDAlu insertion as the culprit.   It was inserted as a headword BEFORE THE META LINE CONVERSION.   Hence, all the L-numbers  of words appearing after kroDAlu in MD had their L-numbers incremented by one.

Solution:  
* remove kroDAlu from the manualByLine02.txt changes that construct md3.txt from md2.txt.
* remake the meta-line file based on md3
* insert the kroDAlu headword into the meta-line version  (with intermediate L=6478.1).
* redo sanhw1/2
   Now the diff does not have all those MD cases with incremented L-nums;  just the 1 extra 6478.1 for
   kroDAlu (and a few others due to those extra AP90 people/places headwords).

Let's give polite applause to this virtue of the meta-line format -- L-num stability over insertion/deletions of headwords.

**Comment by drdhaval2785** [comment]
Polite?
Hip hip hurrayyy

**Comment by gasyoun** [comment]
> most of the
differences were because of an increment of 1 in the L-number of headwords in MD

Heh.

> Let's give polite applause to this virtue of the meta-line format -- L-num stability over insertion/deletions of headwords.

It's a hell. Personally, I do not care about the L numbers yet. When we start to interlink - oh that will be a mess, but know...
