### ISSUE TITLE
SCH vs VCP corrections

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#407]
```
SCH:vfsIdaRqa:vfzIdaRqa:t
SCH:ananravAya:ananvavAya:t
SCH:nfjvAtA:nfjvAlA:t
SCH:mIDvaMs:mIQvaMs:p
```
Above below both are 'z'. 
Discussion welcome. 
![capture](https://user-images.githubusercontent.com/5755132/30029495-0d85794a-91a7-11e7-9cf5-6aad1d499cc0.png)

![capture](https://user-images.githubusercontent.com/5755132/30029570-615e64a0-91a7-11e7-964a-be069439e845.png)
![capture](https://user-images.githubusercontent.com/5755132/30034388-a2e06114-91be-11e7-9d0d-cc5f0dd84e85.png)

Print error. Confirmed by spelling of feminine in the entry itself.
![capture](https://user-images.githubusercontent.com/5755132/30034436-0637a330-91bf-11e7-96b6-f3773ac7ca21.png)

**Comment by drdhaval2785** [comment]
Unable to locate.
http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=SCH&key=avaSyakavandanAniryukti

Can anyone please help locate the headword on the page.
My hunch is, it should be AvaSyaka.

**Comment by gasyoun** [comment]
> My hunch is, it should be AvaSyaka.

Agree.

![ava](https://user-images.githubusercontent.com/80761/30036861-7129dc62-91bf-11e7-827b-a776386f711f.PNG)

**Comment by funderburkjim** [comment]
I think 'avasAyaka' is correct; mw also has this word.  And PWG has avasAya.

**Comment by SergeA** [comment]
> My hunch is, it should be AvaSyaka.

Yes, SCH p.388 begins with **AvaSyaka**vandanAniryukti.

**Comment by funderburkjim** [comment]
> AvaSyakavandanAniryukti.

Part of the problem (in addition to the fact that the initial letter should be a long A), is that the
entry is MISPLACED in the digitization.

In sch.txt,  the (mis-spelled)  `avaSyakavandanAniryukti` appears between `avalepya` and `avasara`, which
occur on page 385.  However, 
* In the print of [page 385, col. 3](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=SCH&page=385),  avalepya and avasara are consecutive headwords.
* The (corrected) `AvaSyakavandanAniryukti` should, appear in the digitization as the first word of [page 388](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=SCH&page=388), before āvis, as @SergeA discovered.

There are also some words in the [second column of page 386](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=SCH&page=386) which are also out of order in the digitization:
```
asaṅga OK
asaṃcārin   >> after asamānarṣi
asadācāra
asamānarṣi
asaṃpāta through astasaṃkhyam  OK
astrapāraga >> after asra
asthibīja OK
asparśanīya >> after asparśanīya (assumeing it is already moved after asra)
asvaka OK
```
And on [page 387, col 3, bottom](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=SCH&page=387), there is a miscoding of ālekhyarūpa, which incorrectly absorbs the
next headword āvarjanā;  the current effect of this is that AvarjanA is not recognized as a headword.

Corrections of these will require various surgeries (insertions/deletions) to sch.txt.
Since no manual changes have been made since the meta-line conversion of sch, I'll do these in the
subdirectory where the meta-line conversion was done, and just after the file constructed in that
conversion.

Sigh.

**Comment by drdhaval2785** [comment]
Sigh-able indeed.

**Comment by funderburkjim** [comment]
### corrections installed
The headword errors described in previous comment now corrected.

**Comment by funderburkjim** [comment]
@drdhaval2785   Here is the manual change file used.
[manualByLine_hworder.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/files/1283417/manualByLine_hworder.txt)

It might be useful to you  as a model in constructing the update transactions for the acc extra headwords.
