### ISSUE TITLE
Todo list for volunteers

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#44]
Hello volunteers,
Thanks for your interest in helping making the Cologne dictionaries clean.
We have created some list of suspicious looking entries in Cologne dictionaries [here](https://drdhaval2785.github.io/dictwiseerrors3-table.html).
Out of these CAE, PW, SKD, SHS and VCP have been checked.
The remaining dictionaries remain to be checked for corrections. 
Someone with some knowledge of Sanskrit will have to check it from the scan pages and submit corrections. Sample of how to submit corrections can be seen at https://github.com/sanskrit-lexicon/CORRECTIONS/issues/39.
Video tutorial of how to reach to the scanned pages and submit corrections is available [here](https://www.youtube.com/watch?v=rKZ_OsSHwsY).

**Comment by gasyoun** [comment]
@drdhaval2785 can we regenerate the list, please? I checked `AP90` and am ready to finish the task in one month from now, but it seems some are fixed by now, lik `Atnya` or kziptu, which gives just क्षिप्, so is linking to nowhere. `AP` - has many broken links as well. I can only propose that in 2015 some of these spelling mistakes were fixed in another topic.
I see that not all links are broken, `uzwwa` or `vaktka` seem to be true words in `CAE`. The checked CAE, PW, SKD, SHS and VCP dictionaries have been integrated, @funderburkjim, what is the status update?

**Comment by gasyoun** [comment]
@drdhaval2785 after a year thinks the method is not as productive as others.

**Comment by drdhaval2785** [comment]
Time to close this issue. Todos change with time.
This issue is done - out and over.
